apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: model-storage-route
spec:
  http:
    - name: prediction
      match:
        hosts:
        - localhost
        paths:
          - /v1/model-store/*
      backends:
        - serviceName: model-storage-service
          servicePort: 80