apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: sso-server-route
spec:
  http:
    - name: authentication
      match:
        hosts:
          - "localhost"
        paths:
          - "/auth*"
          - "/realms*"
          - "/resource*"
          - "/admin*"
          - "/js*"
      backends:
        - serviceName: sso-server-service
          servicePort: 80
