apiVersion: v1
kind: Secret
metadata:
  name: certificates
type: Opaque
data:
  cert: |-
        {{ .Files.Get "files/certificate.crt" | b64enc }}
  key: |-
        {{ .Files.Get "files/privateKey.key" | b64enc }}