apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-server-deployment
  labels:
    app: sso-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-server
  template:
    metadata:
      labels:
        app: sso-server
    spec:
      containers:
      - name: sso-server
        image: sso-server:1.0
        ports:
        - name: https
          containerPort: 8443
        - name: http
          containerPort: 8080
        env:
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME
          value: {{ .Values.sso.hostname | quote }}
        - name: KC_DB_URL
          value: {{ include "sso-db-url" . | trim | quote }}
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: sso-db-credentials
              key: username
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sso-db-credentials
              key: password
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: sso-server-credentials
              key: username
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sso-server-credentials
              key: password