apiVersion: v1
kind: Secret
metadata:
  name: identity-provider-secret
type: Opaque
stringData:
  identity_provider_config.json: |-
    {
      "providerId": "google",
      "alias": "google",
      "enabled": true,
      "config": {
        "clientId": {{ .Values.sso.client_id | quote }},
        "clientSecret": {{ .Values.sso.client_secret | quote }}
      }
    }