apiVersion: v1
kind: Secret
metadata:
  name: identity-provider-secret
type: Opaque
stringData:
  public_client_config.json: |-
    {
       "clientId": {{ .Values.sso.public_client.client_id | quote }},
       "clientAuthenticatorType": "client-secret",
       "protocol": "openid-connect",
       "enabled": true,
       "standardFlowEnabled": false,
       "serviceAccountsEnabled": false,
       "implicitFlowEnabled": false,
       "directAccessGrantsEnabled": true,
       "publicClient": true,
       "bearerOnly": false
     }
  ingress_client_config.json: |-
    {
       "clientId": {{ .Values.sso.ingress_client.client_id | quote }},
       "secret": {{ .Values.sso.ingress_client.client_secret | quote }},
       "clientAuthenticatorType": "client-secret",
       "protocol": "openid-connect",
       "enabled": true,
       "standardFlowEnabled": true,
       "serviceAccountsEnabled": true,
       "implicitFlowEnabled": false,
       "directAccessGrantsEnabled": false,
       "publicClient": false,
       "bearerOnly": false,
       "redirectUris": [
         "*"
       ]
     }