apiVersion: v1
kind: Secret
metadata:
  name: identity-provider-secret
type: Opaque
stringData:
  identity_provider_config.json: |-
    {
      "providerId": "google",
      "alias": "google",
      "enabled": true,
      "config": {
        "clientId": {{ .Values.sso.identity_provider.client_id | quote }},
        "clientSecret": {{ .Values.sso.identity_provider.client_secret | quote }}
      }
    }
  ingress_client_config.json: |-
    {
       "clientId": {{ .Values.sso.ingress_client.client_id | quote }},
       "secret": {{ .Values.sso.ingress_client.client_secret | quote }},
       "clientAuthenticatorType": "client-secret",
       "protocol": "openid-connect",
       "enabled": true,
       "standardFlowEnabled": true,
       "serviceAccountsEnabled": true,
       "implicitFlowEnabled": false,
       "directAccessGrantsEnabled": false,
       "publicClient": false,
       "bearerOnly": false,
       "redirectUris": [
         "*"
       ]
     }