apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.sso.serviceName }}
spec:
  selector:
    app: sso-server
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080