apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-orchestrator-deployment
  labels:
    app: model-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-orchestrator
  template:
    metadata:
      labels:
        app: model-orchestrator
    spec:
      serviceAccountName: model-orchestrator-service-account
      containers:
      - name: model-orchestrator
        image: model-orchestrator:1.0
        ports:
        - containerPort: 80
        env:
        - name: MODEL_STORAGE_PROTO
          value: {{ .Values.model.storage.proto }}
        - name: MODEL_STORAGE_HOST
          value: {{ .Values.model.storage.host }}
        - name: MODEL_STORAGE_PORT
          value: {{ .Values.model.storage.port | quote }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: REDIS_CHANNEL
          value: {{ .Values.redis.channel }}