apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: model-orchestrator-role
rules:
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "delete"
  - apiGroups:
      - "extensions"
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "delete"