apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server-deployment
  labels:
    app: model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: model-server:0.1
        ports:
        - containerPort: 5000