apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: model-prediction-aggregator-route
spec:
  http:
    - name: path
      match:
        hosts:
        - weedrecognition.com
        paths:
          - /v1/model/predict
      backends:
        - serviceName: model-prediction-aggregator-service
          servicePort: 80