apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: model-prediction-aggregator-route
spec:
  http:
    - name: browser-path
      match:
        hosts:
        - localhost
        paths:
          - /v1/model/predict
      backends:
        - serviceName: model-prediction-aggregator-service
          servicePort: 80