apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-prediction-aggregator-deployment
  labels:
    app: model-prediction-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-prediction-aggregator
  template:
    metadata:
      labels:
        app: model-prediction-aggregator
    spec:
      serviceAccountName: model-prediction-aggregator-service-account
      containers:
      - name: model-prediction-aggregator
        image: model-prediction-aggregator:1.0
        ports:
        - containerPort: 80
        env:
          - name: ACTIVATED_MODEL_DB_SOCKET
            value: /var/run/redis/redis.socket
          - name: ACTIVATED_MODEL_KEY
            value: activated_models
          - name: ARCHIVE_DIR
            value: /data
        volumeMounts:
          - mountPath: /var/run/redis
            name: redis-socket
          - mountPath: /data
            name: image-archive
      - name: model-activation-listener
        image: model-activation-listener:1.0
        env:
          - name: LABEL_SELECTOR_FOR_MODEL_PREDICATE_SERVICES
            value: "managed_by=model-orchestrator"
          - name: REDIS_HOST
            value: {{ .Values.redis.host }}
          - name: REDIS_PORT
            value: {{ .Values.redis.port | quote}}
          - name: REDIS_CHANNEL
            value: {{ .Values.redis.channel }}
          - name: ACTIVATED_MODEL_DB_SOCKET
            value: /var/run/redis/redis.socket
          - name: ACTIVATED_MODEL_KEY
            value: activated_models
        volumeMounts:
          - mountPath: /var/run/redis
            name: redis-socket
      - name: activated-model-db
        image: redis:7.0-rc
        volumeMounts:
          - mountPath: /data
            name: activated-model-data-volume
          - mountPath: /var/run/redis
            name: redis-socket
        command:
          - redis-server
          - --save 60 1
          - --unixsocket /var/run/redis/redis.socket
      volumes:
      - name: activated-model-data-volume
        emptyDir: {}
      - name: image-archive
        emptyDir: {}
      - name: redis-socket
        emptyDir: {}