apiVersion: v1
kind: Service
metadata:
  name: model-prediction-aggregator-service
spec:
  selector:
    app: model-prediction-aggregator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80