apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-db-service-name" . | trim | quote }}
spec:
  selector:
    app: sso-db-server
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432