sso:
  client_id: model-administration
  client_secret: wnaKjc2zmgEV9PvBTkbnsr1jsFrWg0Qf
  discovery_url: http://sso-server-service/realms/weed_rec_admin_realm/.well-known/openid-configuration
  realm: weed_rec_admin_realm